units_dict = {
    'width':{
        'c':'centimeter',
        'cm': 'centimeter',
        'm': 'meter',
        'mm': 'millimeter',
        'i':'inch',
        'in': 'inch',
        'f':'foot',
        'ft': 'foot',
        'y':'yard',
        'yd': 'yard'
    },

    'depth':{
        'c':'centimeter',
        'cm': 'centimeter',
        'm': 'meter',
        'mm': 'millimeter',
        'i':'inch',
        'in': 'inch',
        'f':'foot',
        'ft': 'foot',
        'y':'yard',
        'yd': 'yard'
    },

   'height':{
        'c':'centimeter',
        'cm': 'centimeter',
        'm': 'meter',
        'mm': 'millimeter',
        'i':'inch',
        'in': 'inch',
        'f':'foot',
        'ft': 'foot',
        'y':'yard',
        'yd': 'yard'
    },

    'item_weight':{
        'g': 'gram',
        'k':'kilogram',
        'kg': 'kilogram',
        'µ':'microgram',
        'u':'microgram',
        'µg': 'microgram',
        'm':'milligram',
        'mg': 'milligram',
        'o':'ounce',
        'oz': 'ounce',
        'l':'pound',
        'lb': 'pound',
        't': 'ton'
    },
    'maximum_weight_recommendation': {
        'g': 'gram',
        'k':'kilogram',
        'kg': 'kilogram',
        'µ':'microgram',
        'u':'microgram',
        'µg': 'microgram',
        'm':'milligram',
        'mg': 'milligram',
        'o':'ounce',
        'oz': 'ounce',
        'l':'pound',
        'lb': 'pound',
        't': 'ton'
    },
    'voltage':{'k':'kilovolt','kv': 'kilovolt','m':'millivolt','mv': 'millivolt','v': 'volt'},
    'wattage':{'k':'kilowatt','kw': 'kilowatt','w': 'watt'},

    'item_volume':{
        'l': 'liter',
        'm':'milliliter',
        'ml': 'milliliter',
        'c':'centiliter',
        'cl': 'centiliter',
        'd':'deciliter',
        'dl': 'deciliter',
        'u':'microliter',
        'µ':'microliter',
        'µl': 'microliter',
        'f':'cubic foot',
        'ft':'cubic foot',
        'ft³': 'cubic foot',
        'i':'cubic inch',
        'in':'cubic inch',
        'in³': 'cubic inch',
        'cu':'cup',
        'cup': 'cup',
        'fl':'fluid ounce',
        'flo':'fluid ounce',
        'floz': 'fluid ounce',
        'g':'gallon',
        'ga':'gallon',
        'gal': 'gallon',
        'im':'imperial gallon',
        'imp':'imperial gallon',
        'impgal': 'imperial gallon',
        'p':'pint',
        'pt': 'pint',
        'q':'quart',
        'qt': 'quart'
    }
    
}
